const express = require("express");
const router = express.Router();
const { body, validationResult } = require("express-validator");
const Post = require("../models/Post");
const User = require("../models/User");
const Tag = require("../models/Tag");
const { protect } = require("../middleware/auth");
const { cache, redisClient } = require("../utils/redis");

// Auto-tagging algorithm (simple keyword-based)
const generateTags = (title, content) => {
  const text = `${title} ${content}`.toLowerCase();
  const tags = [];

  const keywords = {
    freshwater: [
      "freshwater",
      "tropical",
      "community tank",
      "guppy",
      "tetra",
      "betta",
    ],
    saltwater: ["saltwater", "marine", "reef", "coral", "ocean", "salt"],
    planted: [
      "planted",
      "aquascape",
      "plants",
      "co2",
      "substrate",
      "hardscape",
    ],
    equipment: ["filter", "heater", "lighting", "pump", "air stone"],
    maintenance: ["water change", "testing", "parameters", "maintenance"],
    disease: ["ich", "parasite", "treatment", "medication", "sick"],
  };

  for (const [category, words] of Object.entries(keywords)) {
    const matches = words.filter((word) => text.includes(word));
    if (matches.length >= 1) {
      tags.push({
        tag: category,
        confidence: Math.min(matches.length * 0.3, 0.9),
        autoGenerated: true,
      });
    }
  }

  return tags;
};

// @route   GET /api/posts
// @desc    Get all posts with pagination and filtering
// @access  Public
router.get("/", async (req, res) => {
  try {
    const {
      page = 1,
      limit = 20,
      sort = "-metadata.createdAt",
      tag,
    } = req.query;

    // Generate cache key
    const cacheKey = `posts:${JSON.stringify(req.query)}`;

    // Try to get from cache
    const cachedData = await cache.get(cacheKey);
    if (cachedData) {
      return res.json(cachedData);
    }

    const query = {};

    // Filter by tag
    if (tag) {
      query["tags.tag"] = tag;
    }

    const posts = await Post.find(query)
      .sort(sort)
      .skip((page - 1) * limit)
      .limit(parseInt(limit))
      .populate("user", "username profile.avatar");

    const total = await Post.countDocuments(query);

    const responseData = {
      success: true,
      data: {
        posts,
        pagination: {
          page: parseInt(page),
          limit: parseInt(limit),
          total,
          pages: Math.ceil(total / limit),
        },
      },
    };

    // Cache for 2 minutes
    await cache.set(cacheKey, responseData, 120);

    res.json(responseData);
  } catch (error) {
    console.error("Get Posts Error:", error);
    res.status(500).json({
      success: false,
      error: {
        code: "SERVER_ERROR",
        message: "Error getting posts",
      },
    });
  }
});

// @route   GET /api/posts/search
// @desc    Search posts
// @access  Public
router.get("/search", async (req, res) => {
  try {
    const { q, page = 1, limit = 20 } = req.query;

    if (!q) {
      return res.status(400).json({
        success: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Search query is required",
        },
      });
    }

    const posts = await Post.find({
      $or: [
        { title: { $regex: q, $options: "i" } },
        { content: { $regex: q, $options: "i" } },
      ],
    })
      .sort("-metadata.createdAt")
      .skip((page - 1) * limit)
      .limit(parseInt(limit))
      .populate("user", "username profile.avatar");

    const total = await Post.countDocuments({
      $or: [
        { title: { $regex: q, $options: "i" } },
        { content: { $regex: q, $options: "i" } },
      ],
    });

    res.json({
      success: true,
      data: {
        posts,
        pagination: {
          page: parseInt(page),
          limit: parseInt(limit),
          total,
          pages: Math.ceil(total / limit),
        },
      },
    });
  } catch (error) {
    console.error("Search Posts Error:", error);
    res.status(500).json({
      success: false,
      error: {
        code: "SERVER_ERROR",
        message: "Error searching posts",
      },
    });
  }
});

// @route   GET /api/posts/:postId
// @desc    Get single post
// @access  Public
router.get("/:postId", async (req, res) => {
  try {
    // Generate cache key
    const cacheKey = `post:${req.params.postId}`;

    // Try to get from cache
    const cachedData = await cache.get(cacheKey);
    if (cachedData) {
      return res.json(cachedData);
    }

    const post = await Post.findById(req.params.postId)
      .populate("user", "username profile.avatar profile.bio")
      .populate("engagement.likes", "username");

    if (!post) {
      return res.status(404).json({
        success: false,
        error: {
          code: "NOT_FOUND",
          message: "Post not found",
        },
      });
    }

    // Increment view count (don't cache this change immediately)
    post.metadata.viewCount += 1;
    await post.save();

    const responseData = {
      success: true,
      data: post,
    };

    // Cache for 5 minutes
    await cache.set(cacheKey, responseData, 300);

    res.json(responseData);
  } catch (error) {
    console.error("Get Post Error:", error);
    res.status(500).json({
      success: false,
      error: {
        code: "SERVER_ERROR",
        message: "Error getting post",
      },
    });
  }
});

// @route   POST /api/posts
// @desc    Create new post
// @access  Private
router.post(
  "/",
  protect,
  [
    body("title")
      .trim()
      .isLength({ min: 3, max: 200 })
      .withMessage("Title must be 3-200 characters"),
    body("content")
      .trim()
      .isLength({ min: 10 })
      .withMessage("Content must be at least 10 characters"),
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({
          success: false,
          error: {
            code: "VALIDATION_ERROR",
            message: "Validation failed",
            details: errors.array(),
          },
        });
      }

      const { title, content, tags: manualTags, media } = req.body;

      // Generate auto-tags
      const autoTags = generateTags(title, content);

      // Merge auto-tags with manual tags
      const allTags = [...(manualTags || []), ...autoTags];

      const post = await Post.create({
        user: req.user._id,
        title,
        content,
        tags: allTags,
        media: media || [],
      });

      // Update user's post count
      await User.findByIdAndUpdate(req.user._id, {
        $inc: { "stats.postCount": 1 },
      });

      // Track tag usage - increment usage count for all unique tags
      const uniqueTagNames = [
        ...new Set(allTags.map((t) => t.tag.toLowerCase())),
      ];
      await Promise.all(
        uniqueTagNames.map(async (tagName) => {
          await Tag.findOneAndUpdate(
            { name: tagName },
            { $inc: { usageCount: 1 } },
            { upsert: true, new: true },
          );
        }),
      );

      await post.populate("user", "username profile.avatar");

      res.status(201).json({
        success: true,
        data: post,
        message: "Post created successfully",
      });
    } catch (error) {
      console.error("Create Post Error:", error);
      res.status(500).json({
        success: false,
        error: {
          code: "SERVER_ERROR",
          message: "Error creating post",
        },
      });
    }
  },
);

// @route   PUT /api/posts/:postId
// @desc    Update post
// @access  Private
router.put("/:postId", protect, async (req, res) => {
  try {
    let post = await Post.findById(req.params.postId);

    if (!post) {
      return res.status(404).json({
        success: false,
        error: {
          code: "NOT_FOUND",
          message: "Post not found",
        },
      });
    }

    // Check ownership
    if (post.user.toString() !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        error: {
          code: "FORBIDDEN",
          message: "Not authorized to update this post",
        },
      });
    }

    const { title, content, tags, media } = req.body;
    const updateFields = {};

    if (title) updateFields.title = title;
    if (content) updateFields.content = content;
    if (tags) updateFields.tags = tags;
    if (media) updateFields.media = media;

    post = await Post.findByIdAndUpdate(
      req.params.postId,
      { $set: updateFields },
      { new: true, runValidators: true },
    ).populate("user", "username profile.avatar");

    // Invalidate cache
    await cache.del(`post:${req.params.postId}`);
    await cache.delPattern("posts:*");

    res.json({
      success: true,
      data: post,
      message: "Post updated successfully",
    });
  } catch (error) {
    console.error("Update Post Error:", error);
    res.status(500).json({
      success: false,
      error: {
        code: "SERVER_ERROR",
        message: "Error updating post",
      },
    });
  }
});

// @route   DELETE /api/posts/:postId
// @desc    Delete post
// @access  Private
router.delete("/:postId", protect, async (req, res) => {
  try {
    const post = await Post.findById(req.params.postId);

    if (!post) {
      return res.status(404).json({
        success: false,
        error: {
          code: "NOT_FOUND",
          message: "Post not found",
        },
      });
    }

    // Check ownership
    if (post.user.toString() !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        error: {
          code: "FORBIDDEN",
          message: "Not authorized to delete this post",
        },
      });
    }

    await Post.findByIdAndDelete(req.params.postId);

    // Update user's post count
    await User.findByIdAndUpdate(req.user._id, {
      $inc: { "stats.postCount": -1 },
    });

    // Invalidate cache
    await cache.del(`post:${req.params.postId}`);
    await cache.delPattern("posts:*");

    res.json({
      success: true,
      message: "Post deleted successfully",
    });
  } catch (error) {
    console.error("Delete Post Error:", error);
    res.status(500).json({
      success: false,
      error: {
        code: "SERVER_ERROR",
        message: "Error deleting post",
      },
    });
  }
});

// @route   POST /api/posts/:postId/like
// @desc    Like/unlike post
// @access  Private
router.post("/:postId/like", protect, async (req, res) => {
  try {
    const post = await Post.findById(req.params.postId);

    if (!post) {
      return res.status(404).json({
        success: false,
        error: {
          code: "NOT_FOUND",
          message: "Post not found",
        },
      });
    }

    const likeIndex = post.engagement.likes.indexOf(req.user._id);

    if (likeIndex > -1) {
      // Unlike
      post.engagement.likes.splice(likeIndex, 1);
      post.metadata.likeCount -= 1;
    } else {
      // Like
      post.engagement.likes.push(req.user._id);
      post.metadata.likeCount += 1;
    }

    await post.save();

    // Invalidate cache
    await cache.del(`post:${req.params.postId}`);

    res.json({
      success: true,
      data: {
        liked: likeIndex === -1,
        likeCount: post.metadata.likeCount,
      },
      message: likeIndex === -1 ? "Post liked" : "Post unliked",
    });
  } catch (error) {
    console.error("Like Post Error:", error);
    res.status(500).json({
      success: false,
      error: {
        code: "SERVER_ERROR",
        message: "Error liking post",
      },
    });
  }
});

// @route   POST /api/posts/:postId/bookmark
// @desc    Bookmark/unbookmark post
// @access  Private
router.post("/:postId/bookmark", protect, async (req, res) => {
  try {
    const post = await Post.findById(req.params.postId);

    if (!post) {
      return res.status(404).json({
        success: false,
        error: {
          code: "NOT_FOUND",
          message: "Post not found",
        },
      });
    }

    const bookmarkIndex = post.engagement.bookmarks.indexOf(req.user._id);

    if (bookmarkIndex > -1) {
      // Remove bookmark
      post.engagement.bookmarks.splice(bookmarkIndex, 1);
    } else {
      // Add bookmark
      post.engagement.bookmarks.push(req.user._id);
    }

    await post.save();

    res.json({
      success: true,
      data: {
        bookmarked: bookmarkIndex === -1,
      },
      message: bookmarkIndex === -1 ? "Post bookmarked" : "Bookmark removed",
    });
  } catch (error) {
    console.error("Bookmark Post Error:", error);
    res.status(500).json({
      success: false,
      error: {
        code: "SERVER_ERROR",
        message: "Error bookmarking post",
      },
    });
  }
});

module.exports = router;
