const cloudinary = require("cloudinary").v2;

// Configure Cloudinary if credentials are available
if (
  process.env.CLOUDINARY_CLOUD_NAME &&
  process.env.CLOUDINARY_API_KEY &&
  process.env.CLOUDINARY_API_SECRET
) {
  cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
  });
}

/**
 * Get AI-generated tags from Cloudinary for an image
 * @param {string} imageUrl - The public URL of the image
 * @returns {Promise<Array>} - Array of tags with confidence scores
 */
const getAITags = async (imageUrl) => {
  if (
    !process.env.CLOUDINARY_CLOUD_NAME ||
    !process.env.CLOUDINARY_API_KEY ||
    !process.env.CLOUDINARY_API_SECRET
  ) {
    console.log("Cloudinary not configured, skipping AI tagging");
    return [];
  }

  try {
    // Get the public ID from the URL
    const publicIdMatch = imageUrl.match(/\/v\d+\/(.+?)(?:\.|$)/);
    if (!publicIdMatch) {
      return [];
    }
    const publicId = publicIdMatch[1];

    // Use Cloudinary's context and tags API
    const result = await cloudinary.api.resources_by_ids([publicId], {
      colors: false,
      image_metadata: true,
      context: true,
      tags: true,
    });

    if (result.resources && result.resources.length > 0) {
      const resource = result.resources[0];

      // Get tags from the resource (both manual and AI-generated)
      const tags = resource.tags || [];

      // Map to tag objects with confidence
      return tags.map((tag) => ({
        tag,
        confidence: 0.85, // Cloudinary AI tags typically have high confidence
        autoGenerated: true,
      }));
    }

    return [];
  } catch (error) {
    console.error("Cloudinary AI tagging error:", error);
    return [];
  }
};

/**
 * Generate optimized image transformations for different sizes
 * @param {string} imageUrl - The original image URL
 * @returns {Object} - Object containing different size URLs
 */
const getImageVariants = (imageUrl) => {
  if (!imageUrl.startsWith("http")) {
    // Local file, return as-is
    return {
      original: imageUrl,
      thumbnail: imageUrl,
      medium: imageUrl,
      large: imageUrl,
    };
  }

  // Cloudinary transformations
  const baseUrl = imageUrl.split("/upload/")[0];
  const transform = imageUrl.split("/upload/")[1] || "";

  return {
    original: imageUrl,
    thumbnail: `${baseUrl}/upload/w_200,h_200,c_fill,q_auto,f_auto/${transform}`,
    medium: `${baseUrl}/upload/w_600,h_400,c_fill,q_auto,f_auto/${transform}`,
    large: `${baseUrl}/upload/w_1200,h_800,c_fill,q_auto,f_auto/${transform}`,
  };
};

module.exports = {
  cloudinary,
  getAITags,
  getImageVariants,
};
