import React, { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import {
  Container,
  Typography,
  Box,
  Card,
  CardContent,
  TextField,
  Button,
  Alert,
  CircularProgress,
  Chip,
  IconButton,
} from "@mui/material";
import { Save, ArrowBack, Add, Close } from "@mui/icons-material";
import { fetchPost, updatePost } from "../slices/postsSlice";

const EditPost = () => {
  const { postId } = useParams();
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const { currentPost, loading, error } = useSelector((state) => state.posts);
  const { user, isAuthenticated } = useSelector((state) => state.auth);

  const [formData, setFormData] = useState({
    title: "",
    content: "",
  });
  const [manualTags, setManualTags] = useState("");
  const [tags, setTags] = useState([]);
  const [formErrors, setFormErrors] = useState({});
  const [success, setSuccess] = useState(false);

  useEffect(() => {
    if (postId) {
      dispatch(fetchPost(postId));
    }
  }, [dispatch, postId]);

  useEffect(() => {
    if (currentPost) {
      setFormData({
        title: currentPost.title || "",
        content: currentPost.content || "",
      });
      // Separate manual and auto-generated tags
      const manualTagList = currentPost.tags
        ?.filter((tag) => !tag.autoGenerated)
        .map((tag) => tag.tag);
      setManualTags(manualTagList?.join(", ") || "");
      setTags(currentPost.tags || []);
    }
  }, [currentPost]);

  const isOwner = user?._id === currentPost?.user?._id;

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    if (formErrors[name]) {
      setFormErrors((prev) => ({ ...prev, [name]: "" }));
    }
    setSuccess(false);
  };

  const validateForm = () => {
    const errors = {};
    if (!formData.title.trim()) {
      errors.title = "Title is required";
    } else if (formData.title.length < 3) {
      errors.title = "Title must be at least 3 characters";
    } else if (formData.title.length > 200) {
      errors.title = "Title cannot exceed 200 characters";
    }
    if (!formData.content.trim()) {
      errors.content = "Content is required";
    } else if (formData.content.length < 10) {
      errors.content = "Content must be at least 10 characters";
    } else if (formData.content.length > 10000) {
      errors.content = "Content cannot exceed 10000 characters";
    }
    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!isOwner || !isAuthenticated) {
      return;
    }

    if (!validateForm()) {
      return;
    }

    // Parse manual tags
    const manualTagList = manualTags
      .split(",")
      .map((tag) => tag.trim())
      .filter((tag) => tag.length > 0);

    // Combine manual tags with auto-generated tags
    const autoGeneratedTags = tags.filter((tag) => tag.autoGenerated);
    const allTags = [
      ...manualTagList.map((tag) => ({ tag, autoGenerated: false })),
      ...autoGeneratedTags,
    ];

    const result = await dispatch(
      updatePost({
        postId,
        data: {
          title: formData.title,
          content: formData.content,
          tags: allTags,
        },
      }),
    );

    if (!result.error) {
      setSuccess(true);
    }
  };

  if (!isAuthenticated) {
    return (
      <Container maxWidth="md" sx={{ py: 4 }}>
        <Alert severity="error">Please login to edit posts</Alert>
        <Button
          startIcon={<ArrowBack />}
          onClick={() => navigate("/login")}
          sx={{ mt: 2 }}
        >
          Go to Login
        </Button>
      </Container>
    );
  }

  if (loading) {
    return (
      <Container maxWidth="md" sx={{ py: 4 }}>
        <Box sx={{ display: "flex", justifyContent: "center", py: 8 }}>
          <CircularProgress />
        </Box>
      </Container>
    );
  }

  if (!currentPost) {
    return (
      <Container maxWidth="md" sx={{ py: 4 }}>
        <Alert severity="error">Post not found</Alert>
        <Button
          startIcon={<ArrowBack />}
          onClick={() => navigate("/")}
          sx={{ mt: 2 }}
        >
          Back to Home
        </Button>
      </Container>
    );
  }

  if (!isOwner) {
    return (
      <Container maxWidth="md" sx={{ py: 4 }}>
        <Alert severity="error">You can only edit your own posts</Alert>
        <Button
          startIcon={<ArrowBack />}
          onClick={() => navigate(-1)}
          sx={{ mt: 2 }}
        >
          Go Back
        </Button>
      </Container>
    );
  }

  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Button
        startIcon={<ArrowBack />}
        onClick={() => navigate(`/post/${postId}`)}
        sx={{ mb: 3 }}
      >
        Back to Post
      </Button>

      <Typography variant="h4" component="h1" gutterBottom fontWeight={700}>
        Edit Post 🐠
      </Typography>
      <Typography variant="body1" color="text.secondary" sx={{ mb: 4 }}>
        Update your post content
      </Typography>

      <Card>
        <CardContent sx={{ p: 4 }}>
          {error && (
            <Alert severity="error" sx={{ mb: 3 }}>
              {error}
            </Alert>
          )}

          {success && (
            <Alert severity="success" sx={{ mb: 3 }}>
              Post updated successfully!
            </Alert>
          )}

          <Box component="form" onSubmit={handleSubmit}>
            <TextField
              fullWidth
              label="Title"
              name="title"
              value={formData.title}
              onChange={handleChange}
              error={!!formErrors.title}
              helperText={
                formErrors.title || "Give your post a descriptive title"
              }
              placeholder="e.g., My First Planted Tank Setup"
              sx={{ mb: 3 }}
            />

            <TextField
              fullWidth
              label="Content"
              name="content"
              value={formData.content}
              onChange={handleChange}
              error={!!formErrors.content}
              helperText={
                formErrors.content ||
                "Share your story, ask questions, or give advice"
              }
              multiline
              rows={8}
              sx={{ mb: 3 }}
            />

            {/* Auto-generated Tags Display */}
            {tags.filter((tag) => tag.autoGenerated).length > 0 && (
              <Box sx={{ mb: 3 }}>
                <Typography variant="body2" color="text.secondary" gutterBottom>
                  Auto-generated tags (cannot be removed):
                </Typography>
                <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5 }}>
                  {tags
                    .filter((tag) => tag.autoGenerated)
                    .map((tag, index) => (
                      <Chip
                        key={index}
                        label={tag.tag}
                        size="small"
                        variant="outlined"
                        color="default"
                      />
                    ))}
                </Box>
              </Box>
            )}

            <TextField
              fullWidth
              label="Tags (optional)"
              name="tags"
              value={manualTags}
              onChange={(e) => {
                setManualTags(e.target.value);
                setSuccess(false);
              }}
              placeholder="e.g., freshwater, planted, beginner"
              helperText="Separate tags with commas. These are your custom tags."
              sx={{ mb: 3 }}
            />

            <Box sx={{ display: "flex", gap: 2 }}>
              <Button
                type="submit"
                variant="contained"
                size="large"
                startIcon={
                  loading ? (
                    <CircularProgress size={20} color="inherit" />
                  ) : (
                    <Save />
                  )
                }
                disabled={loading}
              >
                Save Changes
              </Button>
              <Button
                variant="outlined"
                size="large"
                onClick={() => navigate(`/post/${postId}`)}
              >
                Cancel
              </Button>
            </Box>
          </Box>
        </CardContent>
      </Card>
    </Container>
  );
};

export default EditPost;
